/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LimpezasRouteImport } from './routes/limpezas'
import { Route as HospedesRouteImport } from './routes/hospedes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AppRouteImport } from './routes/app'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ImoveisIdRouteImport } from './routes/imoveis.$id'
import { Route as FaxineiraTokenRouteImport } from './routes/faxineira.$token'
import { Route as ApiPublicGeoRouteImport } from './routes/api/public/geo'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LimpezasRoute = LimpezasRouteImport.update({
  id: '/limpezas',
  path: '/limpezas',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedesRoute = HospedesRouteImport.update({
  id: '/hospedes',
  path: '/hospedes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIdRoute = ImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FaxineiraTokenRoute = FaxineiraTokenRouteImport.update({
  id: '/faxineira/$token',
  path: '/faxineira/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeoRoute = ApiPublicGeoRouteImport.update({
  id: '/api/public/geo',
  path: '/api/public/geo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/calendario': typeof CalendarioRoute
  '/hospedes': typeof HospedesRoute
  '/limpezas': typeof LimpezasRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/faxineira/$token': typeof FaxineiraTokenRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/calendario': typeof CalendarioRoute
  '/hospedes': typeof HospedesRoute
  '/limpezas': typeof LimpezasRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/faxineira/$token': typeof FaxineiraTokenRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/calendario': typeof CalendarioRoute
  '/hospedes': typeof HospedesRoute
  '/limpezas': typeof LimpezasRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/faxineira/$token': typeof FaxineiraTokenRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/app'
    | '/calendario'
    | '/hospedes'
    | '/limpezas'
    | '/login'
    | '/signup'
    | '/faxineira/$token'
    | '/imoveis/$id'
    | '/imoveis/'
    | '/api/public/geo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/app'
    | '/calendario'
    | '/hospedes'
    | '/limpezas'
    | '/login'
    | '/signup'
    | '/faxineira/$token'
    | '/imoveis/$id'
    | '/imoveis'
    | '/api/public/geo'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/app'
    | '/calendario'
    | '/hospedes'
    | '/limpezas'
    | '/login'
    | '/signup'
    | '/faxineira/$token'
    | '/imoveis/$id'
    | '/imoveis/'
    | '/api/public/geo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AppRoute: typeof AppRoute
  CalendarioRoute: typeof CalendarioRoute
  HospedesRoute: typeof HospedesRoute
  LimpezasRoute: typeof LimpezasRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  FaxineiraTokenRoute: typeof FaxineiraTokenRoute
  ImoveisIdRoute: typeof ImoveisIdRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
  ApiPublicGeoRoute: typeof ApiPublicGeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpezas': {
      id: '/limpezas'
      path: '/limpezas'
      fullPath: '/limpezas'
      preLoaderRoute: typeof LimpezasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedes': {
      id: '/hospedes'
      path: '/hospedes'
      fullPath: '/hospedes'
      preLoaderRoute: typeof HospedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$id': {
      id: '/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof ImoveisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faxineira/$token': {
      id: '/faxineira/$token'
      path: '/faxineira/$token'
      fullPath: '/faxineira/$token'
      preLoaderRoute: typeof FaxineiraTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geo': {
      id: '/api/public/geo'
      path: '/api/public/geo'
      fullPath: '/api/public/geo'
      preLoaderRoute: typeof ApiPublicGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AppRoute: AppRoute,
  CalendarioRoute: CalendarioRoute,
  HospedesRoute: HospedesRoute,
  LimpezasRoute: LimpezasRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  FaxineiraTokenRoute: FaxineiraTokenRoute,
  ImoveisIdRoute: ImoveisIdRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
  ApiPublicGeoRoute: ApiPublicGeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
