/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PwaCheckRouteImport } from './routes/pwa-check'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LimpezasRouteImport } from './routes/limpezas'
import { Route as HospedesRouteImport } from './routes/hospedes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as AppRouteImport } from './routes/app'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ImoveisIdRouteImport } from './routes/imoveis.$id'
import { Route as FaxineiraTokenRouteImport } from './routes/faxineira.$token'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicGeoRouteImport } from './routes/api/public/geo'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PwaCheckRoute = PwaCheckRouteImport.update({
  id: '/pwa-check',
  path: '/pwa-check',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LimpezasRoute = LimpezasRouteImport.update({
  id: '/limpezas',
  path: '/limpezas',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedesRoute = HospedesRouteImport.update({
  id: '/hospedes',
  path: '/hospedes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIdRoute = ImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FaxineiraTokenRoute = FaxineiraTokenRouteImport.update({
  id: '/faxineira/$token',
  path: '/faxineira/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeoRoute = ApiPublicGeoRouteImport.update({
  id: '/api/public/geo',
  path: '/api/public/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/calendario': typeof CalendarioRoute
  '/demo': typeof DemoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/hospedes': typeof HospedesRoute
  '/limpezas': typeof LimpezasRoute
  '/login': typeof LoginRoute
  '/pwa-check': typeof PwaCheckRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/faxineira/$token': typeof FaxineiraTokenRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/calendario': typeof CalendarioRoute
  '/demo': typeof DemoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/hospedes': typeof HospedesRoute
  '/limpezas': typeof LimpezasRoute
  '/login': typeof LoginRoute
  '/pwa-check': typeof PwaCheckRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/faxineira/$token': typeof FaxineiraTokenRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/calendario': typeof CalendarioRoute
  '/demo': typeof DemoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/hospedes': typeof HospedesRoute
  '/limpezas': typeof LimpezasRoute
  '/login': typeof LoginRoute
  '/pwa-check': typeof PwaCheckRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/faxineira/$token': typeof FaxineiraTokenRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alertas'
    | '/app'
    | '/assinar'
    | '/calendario'
    | '/demo'
    | '/diagnostico'
    | '/equipe'
    | '/financeiro'
    | '/hospedes'
    | '/limpezas'
    | '/login'
    | '/pwa-check'
    | '/signup'
    | '/auth/callback'
    | '/checkout/return'
    | '/convite/$token'
    | '/faxineira/$token'
    | '/imoveis/$id'
    | '/imoveis/'
    | '/api/public/geo'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alertas'
    | '/app'
    | '/assinar'
    | '/calendario'
    | '/demo'
    | '/diagnostico'
    | '/equipe'
    | '/financeiro'
    | '/hospedes'
    | '/limpezas'
    | '/login'
    | '/pwa-check'
    | '/signup'
    | '/auth/callback'
    | '/checkout/return'
    | '/convite/$token'
    | '/faxineira/$token'
    | '/imoveis/$id'
    | '/imoveis'
    | '/api/public/geo'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alertas'
    | '/app'
    | '/assinar'
    | '/calendario'
    | '/demo'
    | '/diagnostico'
    | '/equipe'
    | '/financeiro'
    | '/hospedes'
    | '/limpezas'
    | '/login'
    | '/pwa-check'
    | '/signup'
    | '/auth/callback'
    | '/checkout/return'
    | '/convite/$token'
    | '/faxineira/$token'
    | '/imoveis/$id'
    | '/imoveis/'
    | '/api/public/geo'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertasRoute: typeof AlertasRoute
  AppRoute: typeof AppRoute
  AssinarRoute: typeof AssinarRoute
  CalendarioRoute: typeof CalendarioRoute
  DemoRoute: typeof DemoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EquipeRoute: typeof EquipeRoute
  FinanceiroRoute: typeof FinanceiroRoute
  HospedesRoute: typeof HospedesRoute
  LimpezasRoute: typeof LimpezasRoute
  LoginRoute: typeof LoginRoute
  PwaCheckRoute: typeof PwaCheckRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  FaxineiraTokenRoute: typeof FaxineiraTokenRoute
  ImoveisIdRoute: typeof ImoveisIdRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
  ApiPublicGeoRoute: typeof ApiPublicGeoRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pwa-check': {
      id: '/pwa-check'
      path: '/pwa-check'
      fullPath: '/pwa-check'
      preLoaderRoute: typeof PwaCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpezas': {
      id: '/limpezas'
      path: '/limpezas'
      fullPath: '/limpezas'
      preLoaderRoute: typeof LimpezasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedes': {
      id: '/hospedes'
      path: '/hospedes'
      fullPath: '/hospedes'
      preLoaderRoute: typeof HospedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$id': {
      id: '/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof ImoveisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faxineira/$token': {
      id: '/faxineira/$token'
      path: '/faxineira/$token'
      fullPath: '/faxineira/$token'
      preLoaderRoute: typeof FaxineiraTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geo': {
      id: '/api/public/geo'
      path: '/api/public/geo'
      fullPath: '/api/public/geo'
      preLoaderRoute: typeof ApiPublicGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertasRoute: AlertasRoute,
  AppRoute: AppRoute,
  AssinarRoute: AssinarRoute,
  CalendarioRoute: CalendarioRoute,
  DemoRoute: DemoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EquipeRoute: EquipeRoute,
  FinanceiroRoute: FinanceiroRoute,
  HospedesRoute: HospedesRoute,
  LimpezasRoute: LimpezasRoute,
  LoginRoute: LoginRoute,
  PwaCheckRoute: PwaCheckRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  FaxineiraTokenRoute: FaxineiraTokenRoute,
  ImoveisIdRoute: ImoveisIdRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
  ApiPublicGeoRoute: ApiPublicGeoRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
