/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LimpezasRouteImport } from './routes/limpezas'
import { Route as HospedesRouteImport } from './routes/hospedes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ImoveisIdRouteImport } from './routes/imoveis.$id'

const LimpezasRoute = LimpezasRouteImport.update({
  id: '/limpezas',
  path: '/limpezas',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedesRoute = HospedesRouteImport.update({
  id: '/hospedes',
  path: '/hospedes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIdRoute = ImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/calendario': typeof CalendarioRoute
  '/hospedes': typeof HospedesRoute
  '/limpezas': typeof LimpezasRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis/': typeof ImoveisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/calendario': typeof CalendarioRoute
  '/hospedes': typeof HospedesRoute
  '/limpezas': typeof LimpezasRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis': typeof ImoveisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/calendario': typeof CalendarioRoute
  '/hospedes': typeof HospedesRoute
  '/limpezas': typeof LimpezasRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis/': typeof ImoveisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/calendario'
    | '/hospedes'
    | '/limpezas'
    | '/imoveis/$id'
    | '/imoveis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/calendario'
    | '/hospedes'
    | '/limpezas'
    | '/imoveis/$id'
    | '/imoveis'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/calendario'
    | '/hospedes'
    | '/limpezas'
    | '/imoveis/$id'
    | '/imoveis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CalendarioRoute: typeof CalendarioRoute
  HospedesRoute: typeof HospedesRoute
  LimpezasRoute: typeof LimpezasRoute
  ImoveisIdRoute: typeof ImoveisIdRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/limpezas': {
      id: '/limpezas'
      path: '/limpezas'
      fullPath: '/limpezas'
      preLoaderRoute: typeof LimpezasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedes': {
      id: '/hospedes'
      path: '/hospedes'
      fullPath: '/hospedes'
      preLoaderRoute: typeof HospedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$id': {
      id: '/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof ImoveisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CalendarioRoute: CalendarioRoute,
  HospedesRoute: HospedesRoute,
  LimpezasRoute: LimpezasRoute,
  ImoveisIdRoute: ImoveisIdRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
